sudo: required
services:
  - docker

before_install:
  - docker build -t anandp_pandav/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true anandp_pandav/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-515244902131"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
